### ISSUE TITLE
Better to have an working example.

### ISSUE THREAD

**Issue by manojmanuakku** [gioblu/Cape#1]
Please provide an example that eats this technique.
it will be a bitter remover for beginners.

**Comment by gioblu** [comment]
Thank you, you are absolutely right I should start to stop to ask myself why people doesn't use my code and document it better. I will link you back some documentation soon.

**Comment by gioblu** [comment]
Ciao, I added a brief documentation in the readme, a examples directory will come soon.

**Comment by gioblu** [comment]
Hi manojmanuakku, I added a simple example, corrected readme and I brought the library overflow proof with the addition of the string length as parameter. Let me know what you think about it and close this issue if you are satisfied.
