### ISSUE TITLE
NodeJS Cape

### ISSUE THREAD

**Issue by metroyanno** [gioblu/Cape#10]
Make a npm library of Cape

**Comment by gioblu** [comment]
Ciao @metroyanno, yes that is a good suggestion, I am working on that.

**Comment by eldisniper** [comment]
I wroted gioblu library for node.
https://www.npmjs.com/package/@eldisniper/cape-js
I have tested already with arduino to raspberry through RFID / WIRELESS . And it work :)

**Comment by gioblu** [comment]
Ciao @eldisniper this is a great news :)
I have a few fixes will make a pull request soon.
Compliments and thank you 👍
