### ISSUE TITLE
inverted question mark in serial Monitor

### ISSUE THREAD

**Issue by aimthiazz** [gioblu/Cape#11]
I was tweaking the Serial Hash code (removed the random function of key and salt). Upon running the code my Serial Monitor output is like this, 

![image](https://user-images.githubusercontent.com/14706814/34355761-e41b8f6c-ea5d-11e7-98cf-fd27ce909666.png). 

I tried to take serial output in tera term, and my output like this, 
![image](https://user-images.githubusercontent.com/14706814/34355796-3a07486c-ea5e-11e7-841f-ac2c7df45396.png)

I tried changing the baud rate, but it's no use.

Works fine with other key/salt/message combination.

![image](https://user-images.githubusercontent.com/14706814/34355880-b591bcba-ea5e-11e7-9bc6-39b996b03318.png)

Any Suggestion/Advice would be helpful. TIA

**Comment by gioblu** [comment]
ciao @aimthiazz include the codebase if you can.

**Comment by gioblu** [comment]
Closing, @aimthiazz feel free to reopen if required.
