### ISSUE TITLE
Versioning is not compatible with the Arduino IDE

### ISSUE THREAD

**Issue by gioblu** [gioblu/Cape#15]
Missing minor, and not being full semver the actual versioning make the library not compatible with the Arduino IDE library registry. It obviously would be nice to be part of the libraries listed there. I see it is possible to edit the version number related to a certain release and add to each the missing .0, do you think this is a possible solution? 

This issue was rised by @Pharap here: https://github.com/gioblu/Cape/pull/13

**Comment by Pharap** [comment]
Assuming their FAQ is current and correct then editing the tags on releases is fairly easy to do.
The hard part is that I'm not sure how it applies to the version field in the `library.properties` file.

It might be worth double checking that their FAQ is correct (e.g. by raising an issue) if there's evidence that using a Major.Minor format works alright.

**Comment by gioblu** [comment]
Ciao @Pharap I agree will open now the issue there.

**Comment by Pharap** [comment]
Unfortunately it might be a while before you get a response since it's obviously a popular repo.

**Comment by gioblu** [comment]
@Pharap done: https://github.com/arduino/Arduino/issues/7122

**Comment by gioblu** [comment]
@Pharap got a super fast answer:

> From the library specification (https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format):

> Version should be semver compliant. 1.2.0 is correct; 1.2 is accepted; r5, 003, 1.1c are invalid

> So you should be fine with your current versioning scheme.

So no problem, the issue is solved.

**Comment by Pharap** [comment]
Hrm, I think maybe they're using "should" in the loose sense since "1.2" isn't semver compliant.

**Comment by gioblu** [comment]
Thanks god they do, I prefer using 1.0 instead 1.0.0 because I tend to avoid minor releases and group minor changes until a subversion release has sense to exist. If you look at the PJON releases that is a complex and vast project the 1.0 way fit perfectly its needs.
