### ISSUE TITLE
esp8266 support

### ISSUE THREAD

**Issue by mikeshaulov** [gioblu/Cape#2]
Looks like a useful and simple library and ESP8266 is lacking basic crypto tools.
Any chance to make the library compatible with ESP8266?

Once I try to compile, I get the following warning:

WARNING: library Cape claims to run on [avr] architecture(s) and may be incompatible with your current board which runs on [esp8266] architecture(s).

And then, a bunch of errors related to the swap macro.

**Comment by gioblu** [comment]
Ciao. Thank you for your suggestion I don't know ESP8266 but I will study and try to understand how to make Cape compatible to it.

**Comment by gioblu** [comment]
Ciao Mike, can you please copy here the errors related to macro swap?

**Comment by gioblu** [comment]
@mikeshaulov Ciao! I have removed the swap function and now the encryption method is quite different, so maybe could work :). Could you please give a try to 1.2 with a ESP8266 test? I don't have one here now, I am waiting for it.

Thank you again.
