### ISSUE TITLE
Maximum strength

### ISSUE THREAD

**Issue by ajitam** [gioblu/Cape#4]
Is there a limit on strength? If I run example with strength=10 decode message is not 0K

**Comment by gioblu** [comment]
I will fastly check and give you feedback, thank you for your report.

**Comment by gioblu** [comment]
Hi @ajitam how many bytes is your key?

**Comment by ajitam** [comment]
I've you example. Without modifications

**Comment by gioblu** [comment]
@ajitam you found a bug, I detect the same behaviour. I am working to fix it. Thank you again.

**Comment by gioblu** [comment]
Hi @ajitam I fixed, https://github.com/gioblu/Cape/commit/27e50ff776529eaa44e32c703a7b7edefcb45eee

Readme and example are updated.
Thank you for your report.

**Comment by gioblu** [comment]
I fired encryption strength in favour of the concept of iterations, and seems working really good and seems to give to the user the chance to manage freely and easily dedicated computation time!

**Comment by ajitam** [comment]
update, run, test > works!

So if I understand correctly. From now on, if you provide only `key` in initialization - one (1) iteration is used and no initialization vector?

And as soon as you set iteration as 2 or more - initialization vector is used?
