### ISSUE TITLE
First byte not getting encrypted correctly

### ISSUE THREAD

**Issue by ajitam** [gioblu/Cape#6]
If you output index on line [Cape.cpp:83](https://github.com/gioblu/Cape/blob/master/Cape.cpp#L83)

`Serial.println(i % _key_length - 1);`

You will see that for first `i` there is always `-1` which means that `_key[i % _key_length - 1]` is undefined/unset, therefore data is not encrypted correctly.

p.s.: I decided to go ahead and implement my own version of cipher because there was just to many differences and modifications for my specific project (constantly changing encryption key, optional use of vector,...). But I will keep my eye on this project because I'm working on another project which is more suitable for this implementation.

**Comment by gioblu** [comment]
Fixed, I am sorry for the slow response but I was really busy with PJON.
