### ISSUE TITLE
Change key once program is running

### ISSUE THREAD

**Issue by oldmanegan** [gioblu/Cape#8]
Is there a means of changing the key once the program is running that uses the Cape library? I have the instantiation working fine, but wish to change keys periodically for security reasons without  aneed to restart and find a means to load a new key at start up.

Thanks.

**Comment by gioblu** [comment]
Ciao @oldmanegan. Yes, this is a must have. Thank you for pointing out. I will soon work on it.

**Comment by gioblu** [comment]
Ciao @oldmanegan I have pushed the new version (1.4) containing the change you proposed.
Please if you can give it a test. 
Thank you again.

**Comment by oldmanegan** [comment]
Hi Giovanni,
I tried it several times and could not change the original key. Possibly I am making an error. I set the key instantiation then on the setup() I attempted to modify. Did not work. Must I change it in a standard font ion or the loop()?
Thanks for your work, 

John 

Sent from my iPhone

> On Jul 25, 2016, at 11:56,

**Comment by gioblu** [comment]
`_reduced_key` was not reset correctly on key change. Thank you for pointing out the problem. I developed an example to show how to handle the change, generating a random key every loop cycle.
See the last commits / pull the master version :)

Thank you for pointing out the lack of documentation :).

**Comment by gioblu** [comment]
Ciao @oldmanegan let me know if works now so I will close this issue. 
Thanks again.

**Comment by gioblu** [comment]
https://github.com/gioblu/Cape/releases/tag/1.5

**Comment by oldmanegan** [comment]
All seems well, Giovanni.
Thanks!

**Comment by gioblu** [comment]
Ciao @oldmanegan thank you again for feedback.
Happy tinkering :)

**Comment by oldmanegan** [comment]
By the way, the 1.5 tag link does not work. I only used what is still shown
on Github as 1.4

**Comment by gioblu** [comment]
1.4 contains the bug you noticed, 1.4.1 (See https://github.com/gioblu/Cape/releases/tag/1.4.1) contains the fix.
