### ISSUE TITLE
Decrypt on linux server

### ISSUE THREAD

**Issue by m0lmk** [gioblu/Cape#9]
I'm looking for a way to encrypt a string which I then POST to a remote server. This looks like a good start but is there a way that I can decrypt the string once I have it on a remote server?

**Comment by gioblu** [comment]
Ciao @m0lmk sure use `hash` on both sides if you want a light cipher, use `encrypt` and `decrypt` methods if you want to have stronger encryption.

**Comment by gioblu** [comment]
@m0lmk You should be able to run Cape also on server side if c++ is supported

**Comment by m0lmk** [comment]
Perfect.

Just need to get it working on the arduino now!

Thanks.
